<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>1.ico</ApplicationIcon>
    <Title>WinTop</Title>
    <Description>A real-time system monitor for Windows that displays CPU, memory, network, and process information in a terminal interface.</Description>
    <PackageProjectUrl>https://github.com/Zulwatha/WinTop</PackageProjectUrl>
    <PackageIcon></PackageIcon>
    <RepositoryUrl>https://github.com/Zulwatha/WinTop</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="1.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="9.0.4" />
    <PackageReference Include="System.Management" Version="9.0.4" />
  </ItemGroup>

</Project>
